apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
  labels:
    app: fortune
spec:
  containers:
    - image: jasonlee159/fortune:env
      env:
        - name: "INTERVAL"
          valueFrom:
            configMapKeyRef:
              name: fortune-config
              key: sleep-interval
      name: html-generator
      volumeMounts:
        - mountPath: /var/htdocs
          name: html
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      emptyDir:
        medium: Memory

