apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: nodejs
          image: jasonlee159/kubia:v3
          ports:
            - containerPort: 8080
          readinessProbe:
            periodSeconds: 1
            httpGet:
              port: 8080
              path: /
