apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.extensions.example.com
spec:
  groupPriorityMinimum: 150
  versionPriority: 150
  group: extensions.example.com
  version: v1alpha1
  service:
    name: website-api
    namespace: default
