apiVersion: v1
kind: Pod
metadata:
  name: private-pod
  labels:
    app: fortune
spec:
  imagePullSecrets:
    - name: mydockerhubsecret
  containers:
    - name: main
      image: jasonlee159/fortune
