apiVersion: v1
kind: PodSecurityPolicy
metadata:
  name: pod-as-user-guest
spec:
  containers:
    - name: main
      image: alpine
      command:
        - "/bin/sleep"
        - "999999"
      securityContext:
        runAsUser: 405
